[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/app/web/backend/cache/supervisord.pid

[program:gunicorn]
command=gunicorn --bind 0.0.0.0:8000 config.wsgi:application --env GUNICORN_SERVER=true --access-logfile - --error-logfile - --log-level info --capture-output
directory=/app/web/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery]
command=celery -A config.celery worker --loglevel=info
directory=/app/web/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:celery-beat]
command=celery -A config.celery beat --loglevel=info --schedule=/app/web/backend/cache/celerybeat-schedule
directory=/app/web/backend
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:redis]
command=bash -c 'if [ -n "$REDIS_PASSWORD" ]; then exec redis-server --bind 127.0.0.1 --protected-mode yes --requirepass "$REDIS_PASSWORD" --save ""; else exec redis-server --bind 127.0.0.1 --protected-mode yes --save ""; fi'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
