# Generated by Django 5.0.4 on 2024-12-23 17:15

from django.db import migrations

from django.conf import settings
import psycopg


def connect_to_db():
    db = settings.DATABASES["default"]
    conn = psycopg.connect(dbname=db["NAME"], user=db["USER"],
                           password=db["PASSWORD"], host=db["HOST"], port=db["PORT"])

    cur = conn.cursor()

    return conn, cur


def create_trigger_when_inserting_stations(apps, schema_editor):
    conn, cur = connect_to_db()
    query = f"""
            CREATE OR REPLACE FUNCTION create_stationmeta_from_new_station()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO api_stationmeta (station_id, status_id, remote_access_link, has_battery, battery_description, has_communications, communications_description, comments, navigation_file, navigation_filename, has_gaps, has_gaps_last_update_datetime, has_gaps_update_needed, has_stationinfo)
                VALUES (NEW.api_id, 
                        (SELECT id FROM api_stationstatus WHERE name = 'Active Online' LIMIT 1),
                        '', FALSE, '', FALSE, '', '', '', '',
                        FALSE, NULL, TRUE, FALSE);
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
        """

    try:
        print("Executing: ", query)
        cur.execute(query)
    except Exception as e:
        print(f"Exception ocurred: {e}")
        print("Rolling back...")
        conn.rollback()
        raise
    else:
        conn.commit()
    finally:
        print("---------------------------")

    query = f"""
            CREATE OR REPLACE TRIGGER create_stationmeta_from_new_station_trigger
            AFTER INSERT ON stations
            FOR EACH ROW
            EXECUTE FUNCTION create_stationmeta_from_new_station();
        """

    try:
        print("Executing: ", query)
        cur.execute(query)
    except Exception as e:
        print(f"Exception ocurred: {e}")
        print("Rolling back...")
        conn.rollback()
        raise
    else:
        conn.commit()
    finally:
        print("---------------------------")

    cur.close()
    conn.close()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20241203_1458'),
    ]

    operations = [
        migrations.RunPython(create_trigger_when_inserting_stations)
    ]
