# Generated by Django 5.2.17 on 2026-09-08 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def verify_processing_schema(apps, schema_editor):
    """State-only changes must describe columns already present in the SQL schema."""
    required = {
        'stations': {'NetworkCode'},
        'sources_stations': {'server_id', 'format'},
        'sources_servers': {'format'},
        'rinex_tank_struct': {'KeyCode'},
    }
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        for table, columns in required.items():
            actual = {field.name for field in connection.introspection.get_table_description(cursor, table)}
            if missing := columns - actual:
                raise RuntimeError(f'{table} is missing required processing columns: {sorted(missing)}')
        # The composite processing primary key already enforces uniqueness. Give
        # Django's explicitly named constraint a real database counterpart too.
        constraints = connection.introspection.get_constraints(cursor, 'stationinfo')
        if 'network_code_station_code_date_start_unique' not in constraints:
            cursor.execute('ALTER TABLE stationinfo ADD CONSTRAINT network_code_station_code_date_start_unique UNIQUE ("NetworkCode", "StationCode", "DateStart")')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_antenna_catalog_permissions'),
    ]

    operations = [
        migrations.RunPython(verify_processing_schema),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(model_name='stationinfo', name='antenna_height', field=models.DecimalField(db_column='AntennaHeight', max_digits=6, decimal_places=4, default=0)),
                migrations.AlterField(model_name='stationinfo', name='antenna_north', field=models.DecimalField(db_column='AntennaNorth', max_digits=12, decimal_places=4, default=0)),
                migrations.AlterField(model_name='stationinfo', name='antenna_east', field=models.DecimalField(db_column='AntennaEast', max_digits=12, decimal_places=4, default=0)),
                migrations.AlterModelOptions(
                    name='events',
                    options={'managed': True, 'ordering': ['-event_date']},
                ),
                migrations.AlterModelOptions(
                    name='sourcesservers',
                    options={'managed': True, 'ordering': ['fqdn']},
                ),
                migrations.AddField(
                    model_name='rinextankstruct',
                    name='key_code',
                    field=models.ForeignKey(blank=True, db_column='KeyCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.keys'),
                ),
                migrations.AddField(
                    model_name='sourcesstations',
                    name='format',
                    field=models.ForeignKey(blank=True, db_column='format', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sourcesformats', to_field='format'),
                ),
                migrations.AddField(
                    model_name='sourcesstations',
                    name='server_id',
                    field=models.ForeignKey(db_column='server_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sourcesservers'),
                    preserve_default=False,
                ),
                migrations.AddField(
                    model_name='stations',
                    name='network_code',
                    field=models.ForeignKey(db_column='NetworkCode', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.networks', to_field='network_code'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='earthquakes',
                    name='lat',
                    field=models.DecimalField(decimal_places=50, max_digits=150),
                ),
                migrations.AlterField(
                    model_name='earthquakes',
                    name='lon',
                    field=models.DecimalField(decimal_places=50, max_digits=150),
                ),
                migrations.AlterField(
                    model_name='sourcesformats',
                    name='format',
                    field=models.CharField(unique=True),
                ),
                migrations.AlterUniqueTogether(
                    name='aprcoords',
                    unique_together={('network_code', 'station_code', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='awssync',
                    unique_together={('network_code', 'station_code', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='datasource',
                    unique_together={('network_code', 'station_code', 'try_order')},
                ),
                migrations.AlterUniqueTogether(
                    name='earthquakes',
                    unique_together={('date', 'lat', 'lon')},
                ),
                migrations.AlterUniqueTogether(
                    name='gamithtc',
                    unique_together={('antenna_code', 'height_code')},
                ),
                migrations.AlterUniqueTogether(
                    name='gamitsoln',
                    unique_together={('network_code', 'station_code', 'project', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='gamitsolnexcl',
                    unique_together={('network_code', 'station_code', 'project', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='gamitstats',
                    unique_together={('project', 'subnet', 'year', 'doy', 'system')},
                ),
                migrations.AlterUniqueTogether(
                    name='gamitsubnets',
                    unique_together={('project', 'subnet', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='gamitztd',
                    unique_together={('network_code', 'station_code', 'date', 'project', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='pppsoln',
                    unique_together={('network_code', 'station_code', 'year', 'doy', 'reference_frame')},
                ),
                migrations.AlterUniqueTogether(
                    name='pppsolnexcl',
                    unique_together={('network_code', 'station_code', 'year', 'doy')},
                ),
                migrations.AlterUniqueTogether(
                    name='rinex',
                    unique_together={('network_code', 'station_code', 'observation_year', 'observation_doy', 'interval', 'completion')},
                ),
                migrations.AlterUniqueTogether(
                    name='sourcesstations',
                    unique_together={('network_code', 'station_code', 'try_order')},
                ),
                migrations.AlterUniqueTogether(
                    name='stacks',
                    unique_together={('network_code', 'station_code', 'year', 'doy', 'name')},
                ),
                migrations.AlterUniqueTogether(
                    name='stationalias',
                    unique_together={('network_code', 'station_code')},
                ),
                migrations.AlterUniqueTogether(
                    name='stations',
                    unique_together={('network_code', 'station_code')},
                ),
                migrations.AddConstraint(
                    model_name='stationinfo',
                    constraint=models.UniqueConstraint(fields=('network_code', 'station_code', 'date_start'), name='network_code_station_code_date_start_unique'),
                ),
                migrations.AddField(
                    model_name='sourcesservers',
                    name='format',
                    field=models.ForeignKey(db_column='format', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sourcesformats', to_field='format'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='events',
                    name='event_date',
                    field=models.DateTimeField(db_column='EventDate', default=django.utils.timezone.now),
                ),
                migrations.AlterField(
                    model_name='keys',
                    name='key_code',
                    field=models.CharField(db_column='KeyCode', max_length=7, unique=True),
                ),
                migrations.AlterField(
                    model_name='rinextankstruct',
                    name='key_code',
                    field=models.ForeignKey(blank=True, db_column='KeyCode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.keys', to_field='key_code'),
                ),
                migrations.AlterUniqueTogether(
                    name='events',
                    unique_together={('event_id', 'event_date')},
                ),
            ],
        ),
    ]
